# Generated by Django 3.0.4 on 2020-05-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
